### ISSUE TITLE
Error running `yarn deploy`

### ISSUE THREAD

**Issue by olingern** [TooManyCaptains/TooManyCaptains#9]
Found via Hackernews comment, awesome work!

Unable to currently run `yarn deploy`

![screen shot 2018-02-14 at 2 08 59 pm](https://user-images.githubusercontent.com/1470297/36222897-be815782-1190-11e8-8d2e-95aa7efd563a.png)

Node version:  8.9.1

**Comment by aroman** [comment]
Thanks for your interest in the project, Nick! We hadn't added `surge` to our dependencies — good catch :-) Having said that, you don't want to run that command yourself, as it'll attempt to push your copy of the game live at http://play.toomanycaptains.com.

I've added some more detail to the README for the `game` component, if you're interested in learning more: https://github.com/TooManyCaptains/TooManyCaptains/tree/master/game#whats-in-here
